# Generated by Django 4.0.6 on 2023-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_created',
            field=models.DateField(auto_now=True),
        ),
    ]
